### ISSUE TITLE
conexão MongoDB

### ISSUE THREAD

**Issue by Lutex** [fabriciocovalesci/loterias-caixa-api#2]
Olá Fabricio, estou tentando rodar a aplicação, mas encontro o erro abaixo. Tenho .env configurado com a string do banco de dados, consigo acesso ao banco de dados pelo terminal usando o mongosh, criei o usuario como:

```
db.createUser({
  user: "dbloteria",
  pwd: "dbloteria",
  roles: [
    { role: "root", db: "admin" }
  ]
})
```
 

> node main.js
[Nest] 13964  - 01/08/2024, 11:22:10     LOG [NestFactory] Starting Nest application...
[Nest] 13964  - 01/08/2024, 11:22:10     LOG [InstanceLoader] MongooseModule dependencies initialized +53ms
[Nest] 13964  - 01/08/2024, 11:22:10     LOG [InstanceLoader] HttpModule dependencies initialized +1ms
[Nest] 13964  - 01/08/2024, 11:22:10     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
[Nest] 13964  - 01/08/2024, 11:22:10     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 13964  - 01/08/2024, 11:22:10     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 13964  - 01/08/2024, 11:22:10     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 13964  - 01/08/2024, 11:22:10     LOG [InstanceLoader] ScheduleModule dependencies initialized +1ms
[Nest] 13964  - 01/08/2024, 11:22:10     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 13964  - 01/08/2024, 11:22:40   ERROR [MongooseModule] Unable to connect to the database. Retrying (1)...
[Nest] 13964  - 01/08/2024, 11:23:13   ERROR [MongooseModule] Unable to connect to the database. Retrying (2)...
[Nest] 13964  - 01/08/2024, 11:23:46   ERROR [MongooseModule] Unable to connect to the database. Retrying (3)...
[Nest] 13964  - 01/08/2024, 11:24:19   ERROR [MongooseModule] Unable to connect to the database. Retrying (4)...
[Nest] 13964  - 01/08/2024, 11:24:52   ERROR [MongooseModule] Unable to connect to the database. Retrying (5)...
[Nest] 13964  - 01/08/2024, 11:25:25   ERROR [MongooseModule] Unable to connect to the database. Retrying (6)...
[Nest] 13964  - 01/08/2024, 11:25:58   ERROR [MongooseModule] Unable to connect to the database. Retrying (7)...

**Comment by fabriciocovalesci** [comment]
Olá @Lutex eu adicionei docker e docker-compose assim facilitara na hora de rodar a aplicação.

![Screenshot from 2024-08-02 00-11-49](https://github.com/user-attachments/assets/8ca850af-26d5-4602-91d8-f91916c8e607)

Como esta a sua string de conexao ?

**Comment by Lutex** [comment]
Oi @fabriciocovalesci,

Minha string esta dessa forma, esta correto ?

`CONNECTION_STRING=mongodb://dbloteria:dbloteria@localhost:27017`


Como fiz a instalação direta, sem docker, testei no windows e ubuntu não tive êxito ainda. Vou tentar pelo docker também.
 
Procurei os log do mongodb mas não encontrei a causa do erro de conexão.

**Comment by Lutex** [comment]
Boa @fabriciocovalesci, 

parece que aqui era algum poblema com uso de localhost na string de conexão, alterando para o loopback 127.0.0.01 funcionou.

String atualizada para:

` CONNECTION_STRING=mongodb://<usuario>:<senha>@127.0.0.1:27017`

Abaixo o log completo, porém ao executar as rotas, não recebo o resultado e sim uma página em branco. Mas esse tópico resolvido.

```
>node main.js
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [NestFactory] Starting Nest application...
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [InstanceLoader] MongooseModule dependencies initialized +44ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [InstanceLoader] HttpModule dependencies initialized +1ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [InstanceLoader] EventEmitterModule dependencies initialized +1ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [InstanceLoader] MongooseCoreModule dependencies initialized +47ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [InstanceLoader] MongooseModule dependencies initialized +17ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [InstanceLoader] ScraperModule dependencies initialized +2ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [InstanceLoader] LotteryModule dependencies initialized +0ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [RoutesResolver] AppController {/}: +29ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [RouterExplorer] Mapped {/, GET} route +4ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [RoutesResolver] LotteryController {/api} (version: 1): +0ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [RouterExplorer] Mapped {/api/:lottery, GET} (version: 1) route +1ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [RouterExplorer] Mapped {/api/:lottery/latest, GET} (version: 1) route +1ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [RouterExplorer] Mapped {/api/:lottery/:concurso, GET} (version: 1) route +0ms
[Nest] 8536  - 04/08/2024, 18:05:45     LOG [NestApplication] Nest application successfully started +35ms
```

Valeu!!!
